services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      NEO4J_AUTH: none
    ports:
      - "7474:7474"  # Browser HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
